/*
Pulp 3 API

Testing DistributionsArtifactsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package zest

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/content-services/zest/release"
)

func Test_zest_DistributionsArtifactsApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DistributionsArtifactsApiService DistributionsCoreArtifactsList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.DistributionsArtifactsApi.DistributionsCoreArtifactsList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DistributionsArtifactsApiService DistributionsCoreArtifactsRead", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var artifactDistributionHref string

		resp, httpRes, err := apiClient.DistributionsArtifactsApi.DistributionsCoreArtifactsRead(context.Background(), artifactDistributionHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
