/*
Pulp 3 API

Testing RepositoriesOstreeVersionsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package zest

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/content-services/zest/release/v3"
)

func Test_zest_RepositoriesOstreeVersionsApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test RepositoriesOstreeVersionsApiService RepositoriesOstreeOstreeVersionsDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ostreeOstreeRepositoryVersionHref string

		resp, httpRes, err := apiClient.RepositoriesOstreeVersionsApi.RepositoriesOstreeOstreeVersionsDelete(context.Background(), ostreeOstreeRepositoryVersionHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoriesOstreeVersionsApiService RepositoriesOstreeOstreeVersionsList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ostreeOstreeRepositoryHref string

		resp, httpRes, err := apiClient.RepositoriesOstreeVersionsApi.RepositoriesOstreeOstreeVersionsList(context.Background(), ostreeOstreeRepositoryHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoriesOstreeVersionsApiService RepositoriesOstreeOstreeVersionsRead", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ostreeOstreeRepositoryVersionHref string

		resp, httpRes, err := apiClient.RepositoriesOstreeVersionsApi.RepositoriesOstreeOstreeVersionsRead(context.Background(), ostreeOstreeRepositoryVersionHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoriesOstreeVersionsApiService RepositoriesOstreeOstreeVersionsRepair", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ostreeOstreeRepositoryVersionHref string

		resp, httpRes, err := apiClient.RepositoriesOstreeVersionsApi.RepositoriesOstreeOstreeVersionsRepair(context.Background(), ostreeOstreeRepositoryVersionHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
