/*
Pulp 3 API

Testing PulpAnsibleDefaultApiV3PluginAnsibleSearchCollectionVersionsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package zest

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/content-services/zest/release/v3"
)

func Test_zest_PulpAnsibleDefaultApiV3PluginAnsibleSearchCollectionVersionsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test PulpAnsibleDefaultApiV3PluginAnsibleSearchCollectionVersionsAPIService PulpAnsibleGalaxyDefaultApiV3PluginAnsibleSearchCollectionVersionsList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PulpAnsibleDefaultApiV3PluginAnsibleSearchCollectionVersionsAPI.PulpAnsibleGalaxyDefaultApiV3PluginAnsibleSearchCollectionVersionsList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PulpAnsibleDefaultApiV3PluginAnsibleSearchCollectionVersionsAPIService PulpAnsibleGalaxyDefaultApiV3PluginAnsibleSearchCollectionVersionsRebuild", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PulpAnsibleDefaultApiV3PluginAnsibleSearchCollectionVersionsAPI.PulpAnsibleGalaxyDefaultApiV3PluginAnsibleSearchCollectionVersionsRebuild(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
