/*
Pulp 3 API

Testing PulpMavenApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package zest

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/content-services/zest/release/v3"
)

func Test_zest_PulpMavenApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test PulpMavenApiService PulpMavenGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var name string
		var path string

		httpRes, err := apiClient.PulpMavenApi.PulpMavenGet(context.Background(), name, path).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PulpMavenApiService PulpMavenPut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var name string
		var path string

		httpRes, err := apiClient.PulpMavenApi.PulpMavenPut(context.Background(), name, path).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
