/*
Pulp 3 API

Testing PublicationsVerbatimAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package zest

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/content-services/zest/release/v3"
)

func Test_zest_PublicationsVerbatimAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test PublicationsVerbatimAPIService PublicationsDebVerbatimCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PublicationsVerbatimAPI.PublicationsDebVerbatimCreate(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PublicationsVerbatimAPIService PublicationsDebVerbatimDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var debVerbatimPublicationHref string

		httpRes, err := apiClient.PublicationsVerbatimAPI.PublicationsDebVerbatimDelete(context.Background(), debVerbatimPublicationHref).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PublicationsVerbatimAPIService PublicationsDebVerbatimList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PublicationsVerbatimAPI.PublicationsDebVerbatimList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PublicationsVerbatimAPIService PublicationsDebVerbatimRead", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var debVerbatimPublicationHref string

		resp, httpRes, err := apiClient.PublicationsVerbatimAPI.PublicationsDebVerbatimRead(context.Background(), debVerbatimPublicationHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
