/*
Pulp 3 API

Testing VersionsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package zest

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/content-services/zest/packages/pulpGoBinding"
)

func Test_zest_VersionsApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test VersionsApiService CollectionVersionsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ansibleCollectionVersionHref string

		resp, httpRes, err := apiClient.VersionsApi.CollectionVersionsGet(context.Background(), ansibleCollectionVersionHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VersionsApiService VersionsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ansibleRoleHref string

		resp, httpRes, err := apiClient.VersionsApi.VersionsGet(context.Background(), ansibleRoleHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
